# combined-manifest.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-service
  template:
    metadata:
      labels:
        app: forum-service
    spec:
      containers:
      - name: forum-service
        image: 11112002/forumservice:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  selector:
    app: forum-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5220
