apiVersion: apps/v1
kind: Deployment
metadata:
  name: forumservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forumservice
  template:
    metadata:
      labels:
        app: forumservice
    spec:
      containers:
      - name: forumservice
        image: 11112002/forumservice:latest
        ports:
        - containerPort: 5220
