version: '3.4'

services:
  forumservice:
    image: forumapi:latest
    networks:
        - backend
    build:
      context: .
      dockerfile: ForumAPI/Dockerfile

networks:
  backend:
    name: backend
    external: true
    driver: bridge
